name: friflex_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # core
  get_it: 7.2.0
  injectable: 1.5.3
  dio: 4.0.6
  json_serializable: 6.5.4
  freezed: 2.2.0
  flutter_bloc: 8.1.1
  flutter_dotenv: 5.0.2
  rxdart: 0.27.5

  #localization
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  #utils
  collection: 1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  injectable_generator: 1.5.4
  build_runner: 2.3.2

flutter:

  uses-material-design: true

  assets:
    - .env
    - .env.dev

flutter_intl:
  enabled: true
  main_locale: ru
